#! /usr/bin/env ruby
#--
# PDF::Writer for Ruby.
#   http://rubyforge.org/projects/ruby-pdf/
#   Copyright 2003 - 2005 Austin Ziegler.
#
#   Licensed under a MIT-style licence. See LICENCE in the main distribution
#   for full licensing information.
#
# $Id$
#++

begin
  load 'loader'
rescue LoadError
  load 'bin/loader'
end
ClassLoader.new 'pdf/writer'

require 'pdf/techbook'

PDF::TechBook.run(ARGV)
