#! /usr/bin/env ruby
#--
# PDF::Writer for Ruby.
#   http://rubyforge.org/projects/ruby-pdf/
#   Copyright 2003 - 2005 Austin Ziegler.
#
#   Licensed under a MIT-style licence. See LICENCE in the main distribution
#   for full licensing information.
#
# $Id$
#++
begin
  require 'pdf/techbook'
rescue LoadError => le
  if le.message =~ %r{pdf/techbook$}
    root = File.dirname(File.dirname(File.expand_path(__FILE__)))
    $LOAD_PATH.unshift(File.join(root, "lib"))
    require 'pdf/techbook'
  else
    raise
  end
end

PDF::TechBook.run(ARGV)
